forums/urls.py
from django.urls import re_path
import forums.views as forums

app_name = 'forums'  # ОБЯЗАТЕЛЬНО!!!

urlpatterns = [
    re_path('forum/$', forums.forums, name='forums'),
    re_path('forums/(?P<forum>.*\s*)/$', forums.forum, name='forum'),
    re_path('foruma/(?P<forum>.+\s*)/$', forums.tema, name='categor_forum'),
]

kursach/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.index, name='index'),
    path('android/', mainapp.android, name='android'),
    path('ios/', mainapp.ios, name='ios'),
    path('windows_phone', mainapp.windows, name='windows_phone'),
    path('psp/', mainapp.psp, name='psp'),
    path('xbox/', mainapp.xbox, name='xbox'),
    re_path('^game/(?P<name>.*\s*)/$', mainapp.game, name='game'),
    re_path('^ganre/(?P<gan>.*\s*)/$', mainapp.ganre, name='ganre'),
    re_path('^(?P<os>.*\s*)/ganre/(?P<gan>.*\s*)/$', mainapp.game, name='game'),
    re_path('^news/', include('news.urls', namespace='news')),
    re_path('^forums/', include('forums.urls', namespace='forums')),
    re_path('^auth/', include('user.urls', namespace='auth')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import re_path
import news.views as news

app_name = 'news'  # ОБЯЗАТЕЛЬНО!!!

urlpatterns = [
    re_path('news/$', news.news_all, name='news_all'),
    re_path('game/$', news.news_game, name='news_game'),
    re_path('developers/$', news.news_developers, name='news_developers'),
    re_path('new/(?P<n>.*\s*)/$', news.new, name='new'),
]

user/urls.py
from django.urls import re_path
import user.views as user

app_name = 'user' # ОБЯЗАТЕЛЬНО!!!

urlpatterns = [
    re_path('login/$', user.user_login, name='login'),
    re_path('logout/$', user.user_logout, name='logout'),
    re_path('register/$', user.user_register, name='register'),
    re_path('edit/$', user.user_edit, name='edit'),
    re_path('profile/(?P<id>.*\s*)/$', user.user_profile, name='profile'),
    re_path('message/$', user.user_message, name='message'),
    re_path('message/(?P<id>.*\s*)/$', user.user_message_id, name='message_id'),
]

forums/models.py
from django.db import models
from user.models import User
from mainapp.models import Game, Genre


# Create your models here.
class ForumsRazdel(models.Model):
    name_game = models.ForeignKey(Game, verbose_name='Игра', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Название', max_length=16, unique=True)
    quantity_themes = models.SmallIntegerField(verbose_name='Количество тем', default=0)
    date_create = models.DateTimeField(verbose_name='Добавлена', auto_now_add=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ['date_create']
        verbose_name = 'Раздел форума'
        verbose_name_plural = 'Разделы Форума'


class ForumsTema(models.Model):
    razdel = models.ForeignKey(ForumsRazdel, verbose_name='Раздел', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Название', max_length=16, unique=True)
    author = models.ForeignKey(User, to_field='email', verbose_name='Автор', on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Текст', max_length=2048)
    date_create = models.DateTimeField(verbose_name='Добавлена', auto_now_add=True)
    photo = models.ImageField(verbose_name='Фото', blank=True, upload_to='forumPhoto')
    tema_moder_state = models.BooleanField(verbose_name='Проверил', blank=True, default=False)
    tema_complaint_quantity = models.SmallIntegerField(verbose_name='кол-во жалоб', blank=True, default=0)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ['name', 'date_create']
        verbose_name = 'Тема'
        verbose_name_plural = 'Темы'


class ForumsComment(models.Model):
    forums = models.ForeignKey(ForumsTema, verbose_name='Название темы', on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name='Автор', on_delete=models.CASCADE)
    avatar = models.ImageField(verbose_name='картинка', blank=True, upload_to='forumCommentPhoto')
    text = models.TextField(verbose_name='Текст', max_length=2048)
    date_create = models.DateTimeField(verbose_name='Добавлена', auto_now_add=True)
    com_moder_state = models.BooleanField(verbose_name='Проверил', blank=True, default=False)
    com_complaint_quantity = models.SmallIntegerField(verbose_name='кол-во жалоб', blank=True, default=0)


class ComplaintGCF(models.Model):
    user_complaint = models.ForeignKey(User, verbose_name='Автор жалобы', related_name='автор_ж_т', on_delete=models.CASCADE)
    tema = models.ForeignKey(ForumsComment, verbose_name='Коментарий', on_delete=models.CASCADE)

news/models.py
from django.db import models
from user.models import User
# Create your models here.


class New(models.Model):
    name = models.CharField(verbose_name='Название', max_length=128, unique=True)
    avatar = models.ImageField(verbose_name='Фото', upload_to='newsPhoto')
    desc = models.TextField(verbose_name='Описание', blank=True, max_length=2048)
    date = models.DateTimeField(verbose_name='Добавлена', auto_now_add=True)
    tems = ('игры', 'разработчики', 'другое')

    def __str__(self):
        return f'{self.date} {self.name}'

    class Meta:
        ordering = ['date']
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'


class NewComment(models.Model):
    new_name = models.ForeignKey(New, verbose_name='Название', on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name='Автор', on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Коментарий', blank=True, max_length=548)
    date_added = models.DateTimeField(verbose_name='Добавлен комментария', auto_now_add=True)
    avatar = models.ImageField(verbose_name='Фото комментария', blank=True, upload_to='newCommentPhoto')
    moder_state = models.BooleanField(verbose_name='Проверил', blank=True, default=False)
    complaint_quantity = models.SmallIntegerField(verbose_name='кол-во жалоб', blank=True, default=0)

    def __str__(self):
        return f'{self.date_added} {self.author} {self.new_name}'

    class Meta:
        ordering = ['date_added']
        verbose_name = 'Коментарий'
        verbose_name_plural = 'Коментарии'


class ComplaintGCN(models.Model):
    user_complaint = models.ForeignKey(User, verbose_name='Автор_ж_к_н', on_delete=models.CASCADE)
    comment = models.ForeignKey(NewComment, verbose_name='Коментарий', on_delete=models.CASCADE)

forums/forms.py
import django.forms as forms
from forums.models import ForumsRazdel, ForumsTema, ForumsComment, ComplaintGCF


class ForumsRazdelForm(forms.ModelForm):
    class Meta:
        model = ForumsRazdel
        fields = ('name_game',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ForumsTemaForm(forms.ModelForm):
    class Meta:
        model = ForumsTema
        fields = ('razdel', 'name', 'author', 'text', 'photo')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ForumsCommentForm(forms.ModelForm):
    class Meta:
        model = ForumsComment
        fields = ('avatar', 'text', 'author', 'forums')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ComplaintTemaForm(forms.ModelForm):
    class Meta:
        model = ForumsTema
        fields = ('tema_complaint_quantity',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ComplaintCommentForm(forms.ModelForm):
    class Meta:
        model = ForumsComment
        fields = ('com_complaint_quantity',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ComplaintGCForm(forms.ModelForm):
    class Meta:
        model = ComplaintGCF
        fields = ('user_complaint', 'tema',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

forums/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

from forums.forms import ComplaintGCForm, ForumsCommentForm, ComplaintCommentForm
from user.forms import MyUserCreationForm, MyUserChangeForm
from forums.models import ForumsComment, ForumsRazdel, ForumsTema
from mainapp.models import Genre


def forums(request):
    forums_razdel = ForumsRazdel.objects.all().order_by('date_create')
    forums_tema = ForumsTema.objects.all().order_by('date_create')
    context = {
        'forums_razdel': forums_razdel,
        'forums_tema': forums_tema,
    }
    return render(request, 'forums/index-forum-site.html', context)


def forum(request, forum=None):
    if request.method == 'GET':
        if forum:
            forums_razdel = ForumsRazdel.objects.filter(id=forum).first()
            forums_tema = ForumsTema.objects.filter(razdel=forum).order_by('date_create')
            context = {
                'forums_razdel': forums_razdel,
                'forums_tema': forums_tema,
            }
            return render(request, 'forums/create-new-theme.html', context)


def tema(request, forum=None):
    if request.method == 'GET':
        if forum:
            forums_tema = ForumsTema.objects.filter(id=forum).order_by('date_create')
            comment = ForumsComment.objects.filter(forums=forum)

            context = {
                'comment': comment,
                'forums_tema': forums_tema,
                'forum': forum,
            }
            return render(request, 'forums/themes-post.html', context)

    if request.method == 'POST':
        if 'text' in request.POST and request.POST['text']:
            add_comment = ForumsCommentForm(request.POST, request.FILES)
            if add_comment.is_valid():
                add_comment.save()
                comment = ForumsComment.objects.filter(forums=forum)
                i = 0
                for comm in comment:
                     i = comm.id
                return HttpResponseRedirect(f'/forums/foruma/{forum}/#id_comm{i}')
                # if categor & forum:
                #     forums_tema = ForumsTema.objects.filter(razdel=categor, name=forum).order_by('date_create').first()
                #     comment = ForumsComment.objects.filter(forums=forum)
                #     context = {
                #         'comment': comment,
                #         'forums_tema': forums_tema,
                #     }
                #     return render(request, 'forums/themes-post.html', context)

        # if 'tema_complaint_quantity' in request.POST and request.POST['tema_complaint_quantity']:
        #
        #     complaint_quanti = ForumsComment.objects.filter(id=id).first()
        #     add_complaint = ComplaintCommentForm(request.POST, request.FILES, instance=complaint_quanti)
        #     if add_complaint.is_valid():
        #         complax = ComplaintGCForm(request.POST, request.FILES)
        #         if complax.is_valid():
        #             complax.save()
        #             add_complaint.save()
        #             if forum:
        #                 forums_tema = ForumsTema.objects.filter(name=forum).order_by(
        #                     'date_create').first()
        #                 comment = ForumsComment.objects.filter(forums=forum)
        #                 context = {
        #                     'comment': comment,
        #                     'forums_tema': forums_tema,
        #                 }
        #                 return render(request, 'forums/themes-post.html', context)

        else:
            if forum:
                forums_tema = ForumsTema.objects.filter(id=forum).order_by('date_create')
                comment = ForumsComment.objects.filter(forums=forum)

                context = {
                    'comment': comment,
                    'forums_tema': forums_tema,
                    'forum': forum,
                }
                return render(request, 'forums/themes-post.html', context)
    else:
        if forum:
            forums_tema = ForumsTema.objects.filter(id=forum).order_by('date_create')
            comment = ForumsComment.objects.filter(forums=forum)

            context = {
                'comment': comment,
                'forums_tema': forums_tema,
                'forum': forum,
            }
            return render(request, 'forums/themes-post.html', context)

forums/templates/forums/create-new-theme.html
{% extends 'forums/base.html' %}
{% block content %}

    <div class="create-new-themes">
        <a href="#"><span>Создайте тему</span></a>
    </div>

    <div class="all-posts-on-this-topic">
        <span class="name-theme">{{ forums_razdel.name_game }}</span>
        <div class="all-posts">
            {% for temas in forums_tema %}
                <div class="title-content-date-time-nameAuthor-post">
                    <div class="title-content-post">
                        <a class="{% if request.resolver_match.url_name == 'forums' %}active{% endif %}"
           href="{% url 'forums:categor_forum' temas.id %}"><span class="posts-title">
                    {{ temas.name }}
                </span></a>
                        <span class="posts-content">
                    {{ temas.text|truncatechars:50 }}
                </span>
                    </div>
                    <div class="date-time-authors-post">
                        <a href="{% url 'auth:profile' temas.author.id %}">
                            <span>{{ temas.author.first_name }} {{ temas.author.last_name }}</span>
                        </a>
                        <span>{{ temas.date_create|time:'H:i a' }}</span>
                        <span>{{ temas.date_create|date:'d.m.Y' }}</span>
                    </div>
                </div>
            {% empty %}
                <div>Темы не добавленны</div>
            {% endfor %}
        </div>

    </div>

{% endblock %}

forums/templates/forums/index-forum-site.html
{% extends 'forums/base.html' %}
{% block content %}
<div class="forums-gs-and-recently-added">
    <div class="forums-gs">
        <span class="forums_320px">Форумы GSForums</span>
        {% for razdels in forums_razdel %}
        <div class="themes-forum">
            <div class="named-themes-quantity-themes-asks">
                <a class="{% if request.resolver_match.url_name == 'forums' %}active{% endif %}"
           href="{% url 'forums:forum' razdels.id %}"><span>{{ razdels.name_game }}</span></a>
                <div class="quantity-themes-asks">
                    <span>Тем: {{ razdels.quantity_themes }}</span>
                    <span>Ответов: 999 </span>
                </div>
            </div>
        </div>
            {% empty %}
            <div class="forums-not-added">Форумы не добавленны</div>
        {% endfor %}
    </div>
    <div class="recently-added-themes">
        <span class="recently-themes-title">Недавние темы</span>
        <div class="recently-themes">
            {% for temas in forums_tema %}

            <div class="recently-added-theme-and-quantity-message-this-theme">
                <a class="{% if request.resolver_match.url_name == 'forums' %}active{% endif %}"
           href="{% url 'forums:categor_forum' temas.id %}"><span class="recently-added-theme">{{ temas.name }}</span></a>
                <span class="quantity-message-this-theme" title="Количество сообщений">999</span>
            </div>

            {% empty %}
            <div class="themes-not-added">Темы не добавленны</div>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

forums/templates/forums/themes-post.html
{% extends 'forums/base.html' %}
{% block content %}
    {% for tema in forums_tema %}
        <div class="content-written-by-the-author">
        <div class="post-written-by-the-author">
            <div class="content-post">
            <span class="authors-title">
                {{ tema.name }}
            </span>
                <span class="authors-written">
                {{ tema.text }}
            </span>
            </div>
            <div class="authors-name-date-time">
                <a href="{% url 'auth:profile' tema.author.id %}"><span
                        class="authors-name">{{ tema.author.first_name }} {{ tema.author.last_name }}</span></a>
                <span>{{ temas.date_create|time:'H:i a' }}</span>
                <span>{{ temas.date_create|date:'d.m.Y' }}</span>
                {% if tema.tema_moder_state == 0 and user.is_authenticated %}
                    {% if tema.tema_complaint_quantity == 0 %}
                        <form method="post">
                            <input type="hidden" name="user_complaint" id="id_user_complaint"
                                   value="{{ user.id }}">
                            <input type="hidden" name="tema" id="id_tema" value="{{ tema.id }}">
                            <input type="hidden" name="tema_complaint_quantity" id="id_tema_complaint_quantity"
                                   value="1">
                            <button title="Отправить жалобу" type="submit" class="download-report">
                                <svg fill="orangered" width="25" height="25" viewBox="0.5 2 22 20">
                                    <path d="M2.73,21 L21.26,21 C22.03,21 22.51,20.17 22.13,19.5 L12.86,3.5 C12.47,2.83 11.51,2.83 11.13,3.5 L1.86,19.5 C1.48,20.17 1.96,21 2.73,21 Z M13,18 L11,18 L11,16 L13,16 L13,18 Z M12,14 C11.45,14 11,13.55 11,13 L11,11 C11,10.45 11.45,10 12,10 C12.55,10 13,10.45 13,11 L13,13 C13,13.55 12.55,14 12,14 Z">
                                    </path>
                                </svg>
                            </button>
                        </form>
                    {% elif tema.tema_complaint_quantity == 1 %}
                        <form method="post">
                            <input type="hidden" name="user_complaint" id="id_user_complaint"
                                   value="{{ user.id }}">
                            <input type="hidden" name="tema" id="id_tema" value="{{ tema.id }}">
                            <input type="hidden" name="tema_complaint_quantity" id="id_tema_complaint_quantity"
                                   value="2">
                            <button title="Отправить жалобу" type="submit" class="download-report">
                                <svg fill="orangered" width="25" height="25" viewBox="0.5 2 22 20">
                                    <path d="M2.73,21 L21.26,21 C22.03,21 22.51,20.17 22.13,19.5 L12.86,3.5 C12.47,2.83 11.51,2.83 11.13,3.5 L1.86,19.5 C1.48,20.17 1.96,21 2.73,21 Z M13,18 L11,18 L11,16 L13,16 L13,18 Z M12,14 C11.45,14 11,13.55 11,13 L11,11 C11,10.45 11.45,10 12,10 C12.55,10 13,10.45 13,11 L13,13 C13,13.55 12.55,14 12,14 Z">
                                    </path>
                                </svg>
                            </button>
                        </form>
                    {% elif tema.tema_complaint_quantity == 2 %}
                        <form method="post">
                            <input type="hidden" name="user_complaint" id="id_user_complaint"
                                   value="{{ user.id }}">
                            <input type="hidden" name="tema" id="id_tema" value="{{ tema.id }}">
                            <input type="hidden" name="tema_complaint_quantity" id="id_tema_complaint_quantity"
                                   value="3">
                            <button title="Отправить жалобу" type="submit" class="download-report">
                                <svg fill="orangered" width="25" height="25" viewBox="0.5 2 22 20">
                                    <path d="M2.73,21 L21.26,21 C22.03,21 22.51,20.17 22.13,19.5 L12.86,3.5 C12.47,2.83 11.51,2.83 11.13,3.5 L1.86,19.5 C1.48,20.17 1.96,21 2.73,21 Z M13,18 L11,18 L11,16 L13,16 L13,18 Z M12,14 C11.45,14 11,13.55 11,13 L11,11 C11,10.45 11.45,10 12,10 C12.55,10 13,10.45 13,11 L13,13 C13,13.55 12.55,14 12,14 Z">
                                    </path>
                                </svg>
                            </button>
                        </form>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    {% endfor %}
<div class="comments-left-by-users">
    {% for com in comment %}
        <div class="users-avatar-name-comment" id="id_comm{{ com.id }}">
            <div class="users-avatar"><img src="{{ com.avatar.url }}"></div>
            <div class="users-name-comment">
                <div class="users-name">
                    <a href="{% url 'auth:profile' com.author.id %}">
                        <span>
                            {{ com.author.last_name }} {{ com.author.first_name }}
                        </span>
                    </a>
                    <span>{{ n.date|time:'H:i a' }}</span>
                    <span>{{ n.date|date:'d.m.Y' }}</span>
                    {% if com.com_moder_state == 0 and user.is_authenticated %}
                        {% if com.com_complaint_quantity == 0 %}
                            <form method="post">
                                <input type="hidden" name="user_complaint" id="id_user_complaint"
                                       value="{{ user.id }}">
                                <input type="hidden" name="comment" id="id_comment" value="{{ com.id }}">
                                <input type="hidden" name="com_complaint_quantity" id="id_com_complaint_quantity"
                                       value="1">
                                <button title="Отправить жалобу" type="submit" class="reporting-comment">
                                    <svg fill="orangered" width="25" height="25" viewBox="0.5 2 22 20">
                                        <path d="M2.73,21 L21.26,21 C22.03,21 22.51,20.17 22.13,19.5 L12.86,3.5 C12.47,2.83 11.51,2.83 11.13,3.5 L1.86,19.5 C1.48,20.17 1.96,21 2.73,21 Z M13,18 L11,18 L11,16 L13,16 L13,18 Z M12,14 C11.45,14 11,13.55 11,13 L11,11 C11,10.45 11.45,10 12,10 C12.55,10 13,10.45 13,11 L13,13 C13,13.55 12.55,14 12,14 Z">
                                        </path>
                                    </svg>
                                </button>
                            </form>
                        {% elif com.com_complaint_quantity == 1 %}
                            <form method="post">
                                <input type="hidden" name="user_complaint" id="id_user_complaint"
                                       value="{{ user.id }}">
                                <input type="hidden" name="comment" id="id_comment" value="{{ com.id }}">
                                <input type="hidden" name="com_complaint_quantity" id="id_com_complaint_quantity"
                                       value="2">
                                <button title="Отправить жалобу" type="submit" class="reporting-comment">
                                    <svg fill="orangered" width="25" height="25" viewBox="0.5 2 22 20">
                                        <path d="M2.73,21 L21.26,21 C22.03,21 22.51,20.17 22.13,19.5 L12.86,3.5 C12.47,2.83 11.51,2.83 11.13,3.5 L1.86,19.5 C1.48,20.17 1.96,21 2.73,21 Z M13,18 L11,18 L11,16 L13,16 L13,18 Z M12,14 C11.45,14 11,13.55 11,13 L11,11 C11,10.45 11.45,10 12,10 C12.55,10 13,10.45 13,11 L13,13 C13,13.55 12.55,14 12,14 Z">
                                        </path>
                                    </svg>
                                </button>
                            </form>
                        {% elif tema.com_complaint_quantity == 2 %}
                            <form method="post">
                                <input type="hidden" name="user_complaint" id="id_user_complaint"
                                       value="{{ user.id }}">
                                <input type="hidden" name="comment" id="id_comment" value="{{ com.id }}">
                                <input type="hidden" name="com_complaint_quantity" id="id_com_complaint_quantity"
                                       value="3">
                                <button title="Отправить жалобу" type="submit" class="reporting-comment">
                                    <svg fill="orangered" width="25" height="25" viewBox="0.5 2 22 20">
                                        <path d="M2.73,21 L21.26,21 C22.03,21 22.51,20.17 22.13,19.5 L12.86,3.5 C12.47,2.83 11.51,2.83 11.13,3.5 L1.86,19.5 C1.48,20.17 1.96,21 2.73,21 Z M13,18 L11,18 L11,16 L13,16 L13,18 Z M12,14 C11.45,14 11,13.55 11,13 L11,11 C11,10.45 11.45,10 12,10 C12.55,10 13,10.45 13,11 L13,13 C13,13.55 12.55,14 12,14 Z">
                                        </path>
                                    </svg>
                                </button>
                            </form>
                        {% endif %}
                    {% endif %}
                </div>
                <div class="users-comment">
                    <span>
                    {{ com.text }}
                    </span>
                </div>
            </div>
        </div>
    {% empty %}
        <div>Напиши первый комментарий</div>
    {% endfor %}
        <div class="news-comment-input">
            {% if user.is_authenticated %}
            <form class="news-form_comment" method="post">

                <label class="news-input_comment_label" for="id_avatar">
                    <svg fill="black" width="20px" height="20px" viewBox="0 0 612.675 612.675">
                        <title>Выберите файл</title>
                        <path d="M581.209,223.007L269.839,530.92c-51.592,51.024-135.247,51.024-186.839,0c-51.592-51.023-51.592-133.737,0-184.761
                            L363.248,69.04c34.402-34.009,90.15-34.009,124.553,0c34.402,34.008,34.402,89.166,0,123.174l-280.249,277.12
                            c-17.19,17.016-45.075,17.016-62.287,0c-17.19-16.993-17.19-44.571,0-61.587L394.37,161.42l-31.144-30.793L114.144,376.975
                            c-34.402,34.009-34.402,89.166,0,123.174c34.402,34.009,90.15,34.009,124.552,0l280.249-277.12
                            c51.592-51.023,51.592-133.737,0-184.761c-51.593-51.023-135.247-51.023-186.839,0L36.285,330.784l1.072,1.071
                            c-53.736,68.323-49.012,167.091,14.5,229.88c63.512,62.79,163.35,67.492,232.46,14.325l1.072,1.072l326.942-323.31
                            L581.209,223.007z"/>
                    </svg>
                    <input type="file" name="photo" accept="image/*"
                           id="id_avatar" class="news-input-photo"
                           onchange="showFileName()"/>
                    <input class="news-text_field_comment" title="Напишите комментарий" type="text"
                           placeholder="Напишите комментарий" name="text" id="id_text">
                    <input type="hidden" name="author" id="id_author" value="{{ user.id }}">
                            <input type="hidden" name="forums" id="id_forums" value="{{ forum }}">
                </label>
                <button type="submit" class="news-download-comments" title="Отправить">
                    <svg fill="black" width="25" height="25" viewBox="0 0 32 32">
                        <path d="M19.47,31a2,2,0,0,1-1.8-1.09l-4-7.57a1,1,0,0,1,1.77-.93l4,7.57L29,3.06,3,12.49l9.8,5.26,8.32-8.32a1,1,0,0,1,1.42,1.42l-8.85,8.84a1,1,0,0,1-1.17.18L2.09,14.33a2,2,0,0,1,.25-3.72L28.25,1.13a2,2,0,0,1,2.62,2.62L21.39,29.66A2,2,0,0,1,19.61,31Z"/>
                    </svg>
                </button>
            </form>
                {% else %}
                <div>Войдите в аккаунт что бы написать коментарий. <a href="{% url 'auth:login' %}"> Войти</a></div>
            {% endif %}
        </div>
</div>
</div>
{% endblock %}