forums/urls.py
from django.urls import re_path
import forums.views as forums

app_name = 'forums'  # ОБЯЗАТЕЛЬНО!!!

urlpatterns = [
    re_path('forum/$', forums.forums, name='forums'),
    re_path('forums/(?P<forum>.*\s*)/$', forums.forum, name='forum'),
    re_path('foruma/(?P<forum>.+\s*)/$', forums.tema, name='categor_forum'),
]

kursach/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.index, name='index'),
    path('android/', mainapp.android, name='android'),
    path('ios/', mainapp.ios, name='ios'),
    path('windows_phone', mainapp.windows, name='windows_phone'),
    path('psp/', mainapp.psp, name='psp'),
    path('xbox/', mainapp.xbox, name='xbox'),
    re_path('^game/(?P<name>.*\s*)/$', mainapp.game, name='game'),
    re_path('^ganre/(?P<gan>.*\s*)/$', mainapp.ganre, name='ganre'),
    re_path('^(?P<os>.*\s*)/ganre/(?P<gan>.*\s*)/$', mainapp.game, name='game'),
    re_path('^news/', include('news.urls', namespace='news')),
    re_path('^forums/', include('forums.urls', namespace='forums')),
    re_path('^auth/', include('user.urls', namespace='auth')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import re_path
import news.views as news

app_name = 'news'  # ОБЯЗАТЕЛЬНО!!!

urlpatterns = [
    re_path('news/$', news.news_all, name='news_all'),
    re_path('game/$', news.news_game, name='news_game'),
    re_path('developers/$', news.news_developers, name='news_developers'),
    re_path('new/(?P<n>.*\s*)/$', news.new, name='new'),
]

user/urls.py
from django.urls import re_path
import user.views as user

app_name = 'user' # ОБЯЗАТЕЛЬНО!!!

urlpatterns = [
    re_path('login/$', user.user_login, name='login'),
    re_path('logout/$', user.user_logout, name='logout'),
    re_path('register/$', user.user_register, name='register'),
    re_path('edit/$', user.user_edit, name='edit'),
    re_path('profile/(?P<id>.*\s*)/$', user.user_profile, name='profile'),
    re_path('message/$', user.user_message, name='message'),
    re_path('message/(?P<id>.*\s*)/$', user.user_message_id, name='message_id'),
]

news/models.py
from django.db import models
from user.models import User
# Create your models here.


class New(models.Model):
    name = models.CharField(verbose_name='Название', max_length=128, unique=True)
    avatar = models.ImageField(verbose_name='Фото', upload_to='newsPhoto')
    desc = models.TextField(verbose_name='Описание', blank=True, max_length=2048)
    date = models.DateTimeField(verbose_name='Добавлена', auto_now_add=True)
    tems = ('игры', 'разработчики', 'другое')

    def __str__(self):
        return f'{self.date} {self.name}'

    class Meta:
        ordering = ['date']
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'


class NewComment(models.Model):
    new_name = models.ForeignKey(New, verbose_name='Название', on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name='Автор', on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Коментарий', blank=True, max_length=548)
    date_added = models.DateTimeField(verbose_name='Добавлен комментария', auto_now_add=True)
    avatar = models.ImageField(verbose_name='Фото комментария', blank=True, upload_to='newCommentPhoto')
    moder_state = models.BooleanField(verbose_name='Проверил', blank=True, default=False)
    complaint_quantity = models.SmallIntegerField(verbose_name='кол-во жалоб', blank=True, default=0)

    def __str__(self):
        return f'{self.date_added} {self.author} {self.new_name}'

    class Meta:
        ordering = ['date_added']
        verbose_name = 'Коментарий'
        verbose_name_plural = 'Коментарии'


class ComplaintGCN(models.Model):
    user_complaint = models.ForeignKey(User, verbose_name='Автор_ж_к_н', on_delete=models.CASCADE)
    comment = models.ForeignKey(NewComment, verbose_name='Коментарий', on_delete=models.CASCADE)

news/forms.py
import django.forms as forms
from news.models import New, NewComment, ComplaintGCN


class NewForm(forms.ModelForm):
    class Meta:
        model = New
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class NewCommentForm(forms.ModelForm):
    class Meta:
        model = NewComment
        fields = ('avatar', 'text', 'author', 'new_name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ComplaintForm(forms.ModelForm):
    class Meta:
        model = NewComment
        fields = ('complaint_quantity',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ComplaintGCForm(forms.ModelForm):
    class Meta:
        model = ComplaintGCN
        fields = ('user_complaint', 'comment',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

news/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from news.forms import NewCommentForm, ComplaintForm, ComplaintGCForm
from news.models import New, NewComment


def news_all(request):
    new = New.objects.all()
    print('1')
    context = {
        'new': new,
    }
    return render(request, 'news/news-site.html', context)


def news_game(request):
    new = New.objects.filter()
    context = {
        'new': new,
    }
    return render(request, 'news/game-news-site.html', context)


def news_developers(request):
    new = New.objects.filter()
    print('2')
    context = {
        'new': new,
    }
    return render(request, 'news/developers-news-site.html', context)


def new(request, n=None):
    if request.method == 'GET':
        if n:
            new = New.objects.filter(id=n)
            comment = NewComment.objects.filter(new_name=n)
            context = {
                'new': new,
                'comment': comment,
                'n': n,
            }
            return render(request, 'news/full-information-page-news.html', context)

    if request.method == 'POST':
        if 'text' in request.POST and request.POST['text']:
            add_comment = NewCommentForm(request.POST, request.FILES)
            if add_comment.is_valid():
                add_comment.save()
                comment = NewComment.objects.filter(new_name=n)
                i = 0
                for comm in comment:
                    i = comm.id
                return HttpResponseRedirect(f'/news/new/{n}/#id_comm{i}')
                # йцу
                # if n:
                #     new = New.objects.filter(id=n)
                #     comment = NewComment.objects.filter(new_name=n)
                #     context = {
                #         'new': new,
                #         'comment': comment,
                #         'n': n,
                #     }
                #     return render(request, 'news/full-information-page-news.html', context)

    if 'complaint_quantity' in request.POST and request.POST['complaint_quantity']:
        id = request.POST['comment']
        complaint_quanti = NewComment.objects.filter(id=id).first()
        add_complaint = ComplaintForm(request.POST, request.FILES, instance=complaint_quanti)
        if add_complaint.is_valid():
            complax = ComplaintGCForm(request.POST, request.FILES)
            if complax.is_valid():
                complax.save()
                add_complaint.save()
                if n:
                    new = New.objects.filter(id=n)
                    comment = NewComment.objects.filter(new_name=n)
                    context = {
                        'new': new,
                        'comment': comment,
                        'n': n,
                    }
                    return render(request, 'news/full-information-page-news.html', context)
    else:
        if n:
            new = New.objects.filter(id=n)
            comment = NewComment.objects.filter(new_name=n)
            context = {
                'new': new,
                'comment': comment,
                'n': n,
            }
            return render(request, 'news/full-information-page-news.html', context)

# Create your views here.

news/templates/news/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
        <title>GSNews</title>
    {% endblock %}
    <link rel="stylesheet" href="/static/css/news/style.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
</head>
<body>
<div class="block-site-menu">
    <div class="site-menu">

        <div class="site-logotype">
            <a class="{% if request.resolver_match.url_name == 'news' %}active{% endif %}"
               href="{% url 'news:news_all' %}">
                <span>GSNews</span>
            </a>
        </div>

        <div class="links-to-sites">
            <a class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}"
               href="{% url 'index' %}"><span>GSGames</span></a>
            <a class="{% if request.resolver_match.url_name == 'forums' %}active{% endif %}"
               href="{% url 'forums:forums' %}"><span>GSForum</span></a>
        </div>

        <div class="forum_menu_svg_320px">
            <svg fill="white" width="50" height="50" viewBox="0 0 512 512">
                <path d="M381,190.9H131c-11,0-20-9-20-20s9-20,20-20h250c11,0,20,9,20,20S392,190.9,381,190.9z"/>
                <path d="M381,361.1H131c-11,0-20-9-20-20s9-20,20-20h250c11,0,20,9,20,20S392,361.1,381,361.1z"/>
                <path d="M381,276H131c-11,0-20-9-20-20s9-20,20-20h250c11,0,20,9,20,20S392,276,381,276z"/>
            </svg>
        </div>

        <div class="photo-username-login-logout">
            {% if user.is_authenticated %}
                <div class="photo-and-username">
                    {% if user.avatar %}
                        <div class="users-photo">
                            <img src="{{ user.avatar.url }}" id="user_avatar">
                        </div>
                    {% endif %}
                    <div class="users-name">
                        <a href="{% url 'auth:profile' user.id %}">
                            <span>{{ user.first_name|truncatechars:10 | default:"пользователь" }}</span>
                        </a>
                    </div>
                </div>
            {% endif %}
            <div class="news-login-logout">
                {% if user.is_authenticated %}
                    <a href="{% url 'auth:logout' %}">
                        <svg id="login" viewBox="0 0 17.01 15.87" width="30px" height="30px" fill="red">
                            <title>выход</title>
                            <path d="M266.77 144.53a7.93 7.93 0 1 1-5.6 13.56 8.22 8.22 0 0 1-1.86-2.88h2.34a4.8 4.8 0 0 0 1 1.37 5.81 5.81 0 1 0 0-8.19 6 6 0 0 0-1.09 1.46h-2.32a7.87 7.87 0 0 1 1.89-3 8 8 0 0 1 5.6-2.34z"
                                  transform="translate(-257.71 -144.53)"></path>
                            <path d="M269.54 153.15a.78.78 0 0 0 0-1.23l-2.37-2.54a1.21 1.21 0 0 0-.2-.14 1.24 1.24 0 0 0-.2-.11 1 1 0 0 0-.43-.09h-.23a1 1 0 0 0-.4.17.83.83 0 0 0-.31.31 1.34 1.34 0 0 0-.17.43.56.56 0 0 0 0 .23 1.14 1.14 0 0 0 .09.43.72.72 0 0 0 .11.2.76.76 0 0 0 .14.17l1.37 1.51-1.37 1.51a.76.76 0 0 0-.14.17 1.64 1.64 0 0 0-.11.2 1.29 1.29 0 0 0-.09.46.71.71 0 0 0 0 .23 1.21 1.21 0 0 0 .17.4.83.83 0 0 0 .31.31 1 1 0 0 0 .4.17.71.71 0 0 0 .23 0 1 1 0 0 0 .43-.09.46.46 0 0 0 .2-.11.51.51 0 0 0 .2-.14zm0-1.23z"
                                  transform="translate(-257.71 -144.53)"></path>
                            <path d="M267.89 153v.62h-9.09a1.08 1.08 0 0 1-1.09-1.08 1.08 1.08 0 0 1 1.09-1.08h9.2l-.06.31c0 .14 0 .31-.06.46v.77z"
                                  transform="translate(-257.71 -144.53)"></path>
                        </svg>
                    </a>
                {% else %}
                    <a href="{% url 'auth:login' %}">
                        <svg id="login" viewBox="0 0 17.01 15.87" width="30px" height="30px" fill="green">
                            <title>вход</title>
                            <path d="M266.77 144.53a7.93 7.93 0 1 1-5.6 13.56 8.22 8.22 0 0 1-1.86-2.88h2.34a4.8 4.8 0 0 0 1 1.37 5.81 5.81 0 1 0 0-8.19 6 6 0 0 0-1.09 1.46h-2.32a7.87 7.87 0 0 1 1.89-3 8 8 0 0 1 5.6-2.34z"
                                  transform="translate(-257.71 -144.53)"></path>
                            <path d="M269.54 153.15a.78.78 0 0 0 0-1.23l-2.37-2.54a1.21 1.21 0 0 0-.2-.14 1.24 1.24 0 0 0-.2-.11 1 1 0 0 0-.43-.09h-.23a1 1 0 0 0-.4.17.83.83 0 0 0-.31.31 1.34 1.34 0 0 0-.17.43.56.56 0 0 0 0 .23 1.14 1.14 0 0 0 .09.43.72.72 0 0 0 .11.2.76.76 0 0 0 .14.17l1.37 1.51-1.37 1.51a.76.76 0 0 0-.14.17 1.64 1.64 0 0 0-.11.2 1.29 1.29 0 0 0-.09.46.71.71 0 0 0 0 .23 1.21 1.21 0 0 0 .17.4.83.83 0 0 0 .31.31 1 1 0 0 0 .4.17.71.71 0 0 0 .23 0 1 1 0 0 0 .43-.09.46.46 0 0 0 .2-.11.51.51 0 0 0 .2-.14zm0-1.23z"
                                  transform="translate(-257.71 -144.53)"></path>
                            <path d="M267.89 153v.62h-9.09a1.08 1.08 0 0 1-1.09-1.08 1.08 1.08 0 0 1 1.09-1.08h9.2l-.06.31c0 .14 0 .31-.06.46v.77z"
                                  transform="translate(-257.71 -144.53)"></path>
                        </svg>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="pop_up_window_forum_320px">

    <div class="menu_logotype_quit_forum">
        <svg fill="white" width="25" height="25" viewBox="0 0 612.043 612.043">
            <path d="M397.503,306.011l195.577-195.577c25.27-25.269,25.27-66.213,0-91.482c-25.269-25.269-66.213-25.269-91.481,0
                    L306.022,214.551L110.445,18.974c-25.269-25.269-66.213-25.269-91.482,0s-25.269,66.213,0,91.482L214.54,306.033L18.963,501.61
                    c-25.269,25.269-25.269,66.213,0,91.481c25.269,25.27,66.213,25.27,91.482,0l195.577-195.576l195.577,195.576
                    c25.269,25.27,66.213,25.27,91.481,0c25.27-25.269,25.27-66.213,0-91.481L397.503,306.011z"/>
        </svg>
    </div>

    {% if user.is_authenticated %}
        <a class="user_profile_forum_320px" href="{% url 'auth:profile' user.id %}">
            <div class="photo-and-username_forum_320px">
                {% if user.avatar %}
                    <div class="users-photo_forum_320px">
                        <img src="{{ user.avatar.url }}" id="user_avatar">
                    </div>
                {% endif %}
                <div class="users-name_forum_320px">
                    <span>{{ user.first_name|truncatechars:10 | default:"пользователь" }}</span>
                </div>
            </div>
        </a>
    {% endif %}

    <div class="menus_data_forum">
        <a class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}"
           href="{% url 'index' %}"><span>GSGames</span></a>
        <a class="{% if request.resolver_match.url_name == 'forums' %}active{% endif %}"
           href="{% url 'forums:forums' %}"><span>GSForum</span></a>
    </div>

    <div class="news-login-logout_forum_320px">
        {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">
                <span>Выход</span>
            </a>
        {% else %}
            <a href="{% url 'auth:login' %}">
                <span>Войти</span>
            </a>
        {% endif %}
    </div>

</div>

{% block content %}
    <div class="content_news">

    </div>
{% endblock %}
<script src="/static/js/news/news_script.js"></script>
</body>
</html>

news/templates/news/developers-news-site.html
{% extends 'news/base.html' %}
{% block content %}
    <div class="content_news">
        <div class="news-feed">
            <div class="sorting-by-games-developers">
                <a class="{% if request.resolver_match.url_name == 'news' %}active{% endif %}"
                   href="{% url 'news:news_all' %}"><span class="sorting-by-news">Новости</span></a>
                <a class="{% if request.resolver_match.url_name == 'news' %}active{% endif %}"
                   href="{% url 'news:news_game' %}"><span class="sorting-by-games">Игры</span></a>
                <a class="{% if request.resolver_match.url_name == 'news' %}active{% endif %}"
                   href="{% url 'news:news_developers' %}"><span class="active-developers-news sorting-by-developers">Разработчики</span></a>
            </div>
            <div class="feed">
                {% for n in new %}
                    <div class="news-post-border">
                        <a class="{% if request.resolver_match.url_name == 'news' %}active{% endif %}"
                           href="{% url 'news:new' n.id %}">
                            <div class="news-post">
                                <div class="news-photo"><img src="{{ n.avatar.url }}"></div>
                                <div class="news-text">
                    <span>
                        {{ n.name|truncatechars:50 }}
                    </span>
                                </div>
                            </div>
                        </a>
                        <div class="post-time-and-date">
                            <div class="post-time">{{ n.date|time:'H:i a' }}</div>
                            <div class="post-date">{{ n.date|date:'d.m.Y' }}</div>
                        </div>
                        <div class="post-bottom-border"></div>
                    </div>
                {% empty %}
                    <div class="news-not-added">Новости не добавлены</div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

news/templates/news/full-information-page-news.html
{% extends 'news/base.html' %}

{% block content %}
    <div class="content_news">
        <div class="full-news-information">
            {% for n in new %}
                <div class="news-headline">
        <span>
            {{ n.name }}
        </span>
                </div>
                <div class="news-headline-date-time">
                    <span>{{ n.date|time:'H:i a' }}</span>
                    <span>{{ n.date|date:'d.m.Y' }}</span>
                </div>
                <div class="news-photo"><img src="{{ n.avatar.url }}"></div>
                <div class="news-text">
        <span>
            {{ n.desc }}
        </span>
                </div>
            {% endfor %}
        </div>

        <div class="news-site-comments">
            {% for com in comment %}
                {% if com.complaint_quantity <= 2 and com.moder_state == 0 or com.moder_state == 1 %}
                    <div class="news-commentator" id="id_comm{{ com.id }}">
                        <div class="commentators-photo">
                            <img src="{{ com.author.avatar.url }}">
                        </div>
                        <div class="commentators-name">
            <span>
                {{ com.author.first_name }}
            </span>
                        </div>
                        {% if com.moder_state == 0 %}
                            {% if com.complaint_quantity == 0 %}
                                <form method="post">
                                    <input type="hidden" name="user_complaint" id="id_user_complaint"
                                           value="{{ user.id }}">
                                    <input type="hidden" name="comment" id="id_comment" value="{{ com.id }}">
                                    <input type="hidden" name="complaint_quantity" id="id_complaint_quantity"
                                           value="1">
                                    <button type="submit">пожаловаться</button>
                                </form>
                            {% elif com.complaint_quantity == 1 %}
                                <form method="post">
                                    <input type="hidden" name="user_complaint" id="id_user_complaint"
                                           value="{{ user.id }}">
                                    <input type="hidden" name="comment" id="id_comment" value="{{ com.id }}">
                                    <input type="hidden" name="complaint_quantity" id="id_complaint_quantity"
                                           value="2">
                                    <button type="submit">пожаловаться</button>
                                </form>
                            {% elif com.complaint_quantity == 2 %}
                                <form method="post">
                                    <input type="hidden" name="user_complaint" id="id_user_complaint"
                                           value="{{ user.id }}">
                                    <input type="hidden" name="comment" id="id_comment" value="{{ com.id }}">
                                    <input type="hidden" name="complaint_quantity" id="id_complaint_quantity"
                                           value="3">
                                    <button type="submit">пожаловаться</button>
                                </form>
                            {% endif %}
                        {% endif %}
                    </div>
                    <div class="news-comment-user">
        <span>
            {{ com.text }}
        </span>
                    </div>
                    <div class="date-and-time-sending-comment">
                        <span>{{ com.date_added|time:'H:i a' }}</span>
                        <span>{{ com.date_added|date:'d.m.Y' }}</span>
                    </div>
                {% endif %}
            {% empty %}
                <div>Напиши первый комментарий</div>
            {% endfor %}

            <div class="news-comment-input">
                {% if user.is_authenticated %}
                    <form class="news-form_comment" method="post">

                        <label class="news-input_comment_label" for="id_avatar">
                            <svg fill="black" width="20px" height="20px" viewBox="0 0 612.675 612.675">
                                <title>Выберите файл</title>
                                <path d="M581.209,223.007L269.839,530.92c-51.592,51.024-135.247,51.024-186.839,0c-51.592-51.023-51.592-133.737,0-184.761
                            L363.248,69.04c34.402-34.009,90.15-34.009,124.553,0c34.402,34.008,34.402,89.166,0,123.174l-280.249,277.12
                            c-17.19,17.016-45.075,17.016-62.287,0c-17.19-16.993-17.19-44.571,0-61.587L394.37,161.42l-31.144-30.793L114.144,376.975
                            c-34.402,34.009-34.402,89.166,0,123.174c34.402,34.009,90.15,34.009,124.552,0l280.249-277.12
                            c51.592-51.023,51.592-133.737,0-184.761c-51.593-51.023-135.247-51.023-186.839,0L36.285,330.784l1.072,1.071
                            c-53.736,68.323-49.012,167.091,14.5,229.88c63.512,62.79,163.35,67.492,232.46,14.325l1.072,1.072l326.942-323.31
                            L581.209,223.007z"/>
                            </svg>
                            <input type="file" name="avatar" accept="image/*"
                                   id="id_avatar" class="news-input-photo"
                                   onchange="showFileName()"/>
                            <input class="news-text_field_comment" title="Напишите комментарий" type="text"
                                   placeholder="Напишите комментарий" name="text" id="id_text">
                            <input type="hidden" name="author" id="id_author" value="{{ user.id }}">
                            <input type="hidden" name="new_name" id="id_new_name" value="{{ n }}">
                        </label>
                        <button type="submit" class="news-download-comments" title="Отправить">
                            <svg fill="black" width="30" height="30" viewBox="0 0 32 32">
                                <path d="M19.47,31a2,2,0,0,1-1.8-1.09l-4-7.57a1,1,0,0,1,1.77-.93l4,7.57L29,3.06,3,12.49l9.8,5.26,8.32-8.32a1,1,0,0,1,1.42,1.42l-8.85,8.84a1,1,0,0,1-1.17.18L2.09,14.33a2,2,0,0,1,.25-3.72L28.25,1.13a2,2,0,0,1,2.62,2.62L21.39,29.66A2,2,0,0,1,19.61,31Z"/>
                            </svg>
                        </button>
                    </form>
                {% else %}
                    <div>Войдите в аккаунт что бы написать коментарий. <a href="{% url 'auth:login' %}"> Войти</a></div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

news/templates/news/game-news-site.html
{% extends 'news/base.html' %}
{% block content %}
    <div class="content_news">
        <div class="news-feed">
            <div class="sorting-by-games-developers">
                <a class="{% if request.resolver_match.url_name == 'news' %}active{% endif %}"
                   href="{% url 'news:news_all' %}"><span class="sorting-by-news">Новости</span></a>
                <a class="{% if request.resolver_match.url_name == 'news' %}active{% endif %}"
                   href="{% url 'news:news_game' %}"><span class="active-game-news sorting-by-games">Игры</span></a>
                <a class="{% if request.resolver_match.url_name == 'news' %}active{% endif %}"
                   href="{% url 'news:news_developers' %}"><span class="sorting-by-developers">Разработчики</span></a>
            </div>
            <div class="feed">
                {% for n in new %}
                    <div class="news-post-border">
                        <a class="{% if request.resolver_match.url_name == 'news' %}active{% endif %}"
                           href="{% url 'news:new' n.id %}">
                            <div class="news-post">
                                <div class="news-photo"><img src="{{ n.avatar.url }}"></div>
                                <div class="news-text">
                    <span>
                        {{ n.name|truncatechars:50 }}
                    </span>
                                </div>
                            </div>
                        </a>
                        <div class="post-time-and-date">
                            <div class="post-time">{{ n.date|time:'H:i a' }}</div>
                            <div class="post-date">{{ n.date|date:'d.m.Y' }}</div>
                        </div>
                        <div class="post-bottom-border"></div>
                    </div>
                {% empty %}
                    <div class="news-not-added">Новости не добавлены</div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

news/templates/news/news-site.html
{% extends 'news/base.html' %}
{% block content %}
    <div class="content_news">
        <div class="news-feed">
            <div class="sorting-by-games-developers">
                <a class="{% if request.resolver_match.url_name == 'news_all' %}active{% endif %}"
                   href="{% url 'news:news_all' %}"><span class="active-news sorting-by-news">Новости</span></a>
                <a class="{% if request.resolver_match.url_name == 'news' %}active{% endif %}"
                   href="{% url 'news:news_game' %}"><span class="sorting-by-games">Игры</span></a>
                <a class="{% if request.resolver_match.url_name == 'news' %}active{% endif %}"
                   href="{% url 'news:news_developers' %}"><span class="sorting-by-developers">Разработчики</span></a>
            </div>
            <div class="feed">
                {% for n in new %}
                    <div class="news-post-border">
                        <a class="{% if request.resolver_match.url_name == 'news' %}active{% endif %}"
                           href="{% url 'news:new' n.id %}">
                            <div class="news-post">
                                <div class="news-photo">
                                    <img src="{{ n.avatar.url }}">
                                </div>
                                <div class="news-text">
                    <span>
                        {{ n.name|truncatechars:50 }}
                    </span>
                                </div>
                            </div>
                        </a>
                        <div class="post-time-and-date">
                            <div class="post-time">{{ n.date|time:'H:i a' }}</div>
                            <div class="post-date">{{ n.date|date:'d.m.Y' }}</div>
                        </div>
                        <div class="post-bottom-border"></div>
                    </div>
                {% empty %}
                    <div class="news-not-added">Новости не добавлены</div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}